# Generated by Django 6.0 on 2025-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=24, verbose_name='Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Dekont Dosyası'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tc_no',
            field=models.CharField(blank=True, max_length=11, verbose_name='Okul Numarası'),
        ),
    ]
