# Generated by Django 6.0 on 2025-12-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_customuser_options_customuser_phone_and_more'),
        ('Period', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Period.period', verbose_name='Dönem'),
        ),
    ]
