# Generated by Django 6.0 on 2025-12-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_department_customuser_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Bölüm', 'verbose_name_plural': 'Bölümler'},
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=128, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(max_length=128, verbose_name='Fakülte'),
        ),
    ]
