# Generated by Django 6.0 on 2025-12-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(verbose_name='Başlangıç Yılı')),
                ('finish_year', models.PositiveIntegerField(verbose_name='Bitiş Yılı')),
            ],
            options={
                'verbose_name': 'Dönem',
                'verbose_name_plural': 'Dönemler',
            },
        ),
    ]
